import { parseISODate, toISODate } from "@/lib/date";
import type {
  AdminHistoryEntry,
  AdminMember,
  Dispute,
  Equipment,
  EquipmentCategory,
  Rental,
  Report,
  User,
} from "@/lib/types";

export const EQUIPMENT_CATEGORIES: EquipmentCategory[] = [
  "카메라",
  "노트북",
  "VR기기",
  "프로젝터",
  "게임기",
  "렌즈",
];

/** id of the member the app treats as "logged in" by default. */
export const CURRENT_USER_ID = "m1";

export const USERS: User[] = [
  {
    id: "m1",
    name: "김도현",
    nickname: "doohyun",
    email: "kimdohyun@example.com",
    phone: "010-1234-5678",
    avatarInitials: "김도",
    defaultAddress: {
      recipientName: "김도현",
      phone: "010-1234-5678",
      zipcode: "06236",
      address: "서울특별시 강남구 테헤란로 123",
      detailAddress: "101동 1502호",
    },
  },
  {
    id: "m2",
    name: "이서연",
    nickname: "seoyeon",
    email: "seoyeon.lee@example.com",
    phone: "010-2345-6789",
    avatarInitials: "이서",
    defaultAddress: {
      recipientName: "이서연",
      phone: "010-2345-6789",
      zipcode: "04524",
      address: "서울특별시 중구 세종대로 110",
      detailAddress: "5층",
    },
  },
  {
    id: "m3",
    name: "박준혁",
    nickname: "junhyuk",
    email: "junhyuk.park@example.com",
    phone: "010-3456-7890",
    avatarInitials: "박준",
    defaultAddress: {
      recipientName: "박준혁",
      phone: "010-3456-7890",
      zipcode: "48058",
      address: "부산광역시 해운대구 센텀중앙로 55",
      detailAddress: "202호",
    },
  },
  {
    id: "m4",
    name: "최유나",
    nickname: "yuna",
    email: "yuna.choi@example.com",
    phone: "010-4567-8901",
    avatarInitials: "최유",
    defaultAddress: {
      recipientName: "최유나",
      phone: "010-4567-8901",
      zipcode: "13494",
      address: "경기도 성남시 분당구 판교역로 235",
      detailAddress: "3층 305호",
    },
  },
  {
    id: "m5",
    name: "정민수",
    nickname: "minsu",
    email: "minsu.jung@example.com",
    phone: "010-5678-9012",
    avatarInitials: "정민",
    defaultAddress: {
      recipientName: "정민수",
      phone: "010-5678-9012",
      zipcode: "22004",
      address: "인천광역시 연수구 컨벤시아대로 165",
      detailAddress: "1801호",
    },
  },
];

export function userName(userId: string): string {
  return USERS.find((user) => user.id === userId)?.name ?? "알 수 없음";
}

export const EQUIPMENT: Equipment[] = [
  {
    id: "eq1",
    name: "소니 A7C II 미러리스",
    category: "카메라",
    description:
      "풀프레임 미러리스 카메라입니다. 배터리 2개, 기본 렌즈, 충전기 포함해서 드립니다. 물론 조심히 다뤄주세요!",
    pricePerDay: 25000,
    condition: "양호",
    ownerId: "m2",
    ownerName: userName("m2"),
    status: "공개",
    createdAt: "2026-06-01",
    ratingAverage: 4.8,
    reportCount: 0,
  },
  {
    id: "eq2",
    name: "캐논 EOS R6 Mark II",
    category: "카메라",
    description: "영상 촬영에 최적화된 바디입니다. 짐벌, 마이크는 별도 대여가 필요합니다.",
    pricePerDay: 32000,
    condition: "양호",
    ownerId: "m4",
    ownerName: userName("m4"),
    status: "공개",
    createdAt: "2026-05-20",
    ratingAverage: 4.6,
    reportCount: 0,
  },
  {
    id: "eq3",
    name: "맥북 프로 16 M3",
    category: "노트북",
    description: "M3 Pro 칩, 36GB 메모리. 영상 편집·개발 작업용으로 사용했습니다.",
    pricePerDay: 28000,
    condition: "양호",
    ownerId: "m1",
    ownerName: userName("m1"),
    status: "공개",
    createdAt: "2026-04-10",
    ratingAverage: 4.9,
    reportCount: 0,
  },
  {
    id: "eq4",
    name: "메타 퀘스트 3",
    category: "VR기기",
    description: "컨트롤러 2개, 충전 독 포함. 게임 몇 개 미리 설치되어 있습니다.",
    pricePerDay: 15000,
    condition: "사용감 있음",
    ownerId: "m1",
    ownerName: userName("m1"),
    status: "공개",
    createdAt: "2026-05-02",
    ratingAverage: 4.5,
    reportCount: 1,
  },
  {
    id: "eq5",
    name: "LG 시네빔 4K",
    category: "프로젝터",
    description: "4K UHD 홈 프로젝터. 스크린은 포함되어 있지 않습니다.",
    pricePerDay: 20000,
    condition: "양호",
    ownerId: "m1",
    ownerName: userName("m1"),
    status: "공개",
    createdAt: "2026-03-18",
    ratingAverage: 4.7,
    reportCount: 0,
  },
  {
    id: "eq6",
    name: "플레이스테이션5 슬림",
    category: "게임기",
    description: "듀얼센스 컨트롤러 2개, 인기 타이틀 3종 포함.",
    pricePerDay: 18000,
    condition: "양호",
    ownerId: "m4",
    ownerName: userName("m4"),
    status: "공개",
    createdAt: "2026-02-27",
    ratingAverage: 4.9,
    reportCount: 0,
  },
  {
    id: "eq7",
    name: "소니 FE 24-70mm GM II",
    category: "렌즈",
    description: "F2.8 표준 줌 렌즈. 후드, 파우치 포함.",
    pricePerDay: 12000,
    condition: "양호",
    ownerId: "m5",
    ownerName: userName("m5"),
    status: "공개",
    createdAt: "2026-06-10",
    ratingAverage: 4.8,
    reportCount: 0,
  },
  {
    id: "eq8",
    name: "LG 그램 17",
    category: "노트북",
    description: "초경량 17인치 노트북. 출장·여행용으로 좋습니다.",
    pricePerDay: 16000,
    condition: "사용감 있음",
    ownerId: "m5",
    ownerName: userName("m5"),
    status: "공개",
    createdAt: "2026-01-15",
    ratingAverage: 4.2,
    reportCount: 2,
  },
];

const SHIPPING_TEMPLATE = (recipientId: string) => USERS.find((u) => u.id === recipientId)!.defaultAddress;

export const RENTALS: Rental[] = [
  {
    id: "r1",
    equipmentId: "eq3",
    ownerId: "m1",
    ownerName: userName("m1"),
    borrowerId: "m2",
    borrowerName: userName("m2"),
    status: "PENDING",
    startDate: "2026-08-20",
    endDate: "2026-08-25",
    totalPrice: 28000 * 5,
    message: "출장 촬영 편집용으로 사용하려고 합니다. 잘 부탁드려요!",
    shippingAddress: SHIPPING_TEMPLATE("m2"),
    shipping: null,
    receiptEvidence: null,
    returnEvidence: null,
    createdAt: "2026-08-14",
  },
  {
    id: "r2",
    equipmentId: "eq4",
    ownerId: "m1",
    ownerName: userName("m1"),
    borrowerId: "m3",
    borrowerName: userName("m3"),
    status: "PAID",
    startDate: "2026-08-16",
    endDate: "2026-08-19",
    totalPrice: 15000 * 3,
    message: "친구들이랑 게임 모임에서 쓸 예정입니다.",
    shippingAddress: SHIPPING_TEMPLATE("m3"),
    shipping: null,
    receiptEvidence: null,
    returnEvidence: null,
    createdAt: "2026-08-13",
  },
  {
    id: "r3",
    equipmentId: "eq2",
    ownerId: "m4",
    ownerName: userName("m4"),
    borrowerId: "m1",
    borrowerName: userName("m1"),
    status: "SHIPPING",
    startDate: "2026-08-15",
    endDate: "2026-08-18",
    totalPrice: 32000 * 3,
    message: "제품 촬영용으로 3일만 빌리겠습니다.",
    shippingAddress: SHIPPING_TEMPLATE("m1"),
    shipping: { carrier: "CJ대한통운", trackingNumber: "684512309981" },
    receiptEvidence: null,
    returnEvidence: null,
    createdAt: "2026-08-12",
  },
  {
    id: "r4",
    equipmentId: "eq7",
    ownerId: "m5",
    ownerName: userName("m5"),
    borrowerId: "m1",
    borrowerName: userName("m1"),
    status: "RENTING",
    startDate: "2026-08-06",
    endDate: "2026-08-12",
    totalPrice: 12000 * 6,
    message: "인물 사진 작업에 사용하겠습니다.",
    shippingAddress: SHIPPING_TEMPLATE("m1"),
    shipping: { carrier: "한진택배", trackingNumber: "402981735620" },
    receiptEvidence: {
      photoUrls: ["evidence-r4-receipt-1", "evidence-r4-receipt-2"],
      condition: "양호",
      memo: "렌즈 외관, 마운트 모두 이상 없음.",
      recordedAt: "2026-08-06",
    },
    returnEvidence: null,
    createdAt: "2026-08-03",
  },
  {
    id: "r5",
    equipmentId: "eq1",
    ownerId: "m2",
    ownerName: userName("m2"),
    borrowerId: "m1",
    borrowerName: userName("m1"),
    status: "RETURN_UPLOAD",
    startDate: "2026-08-05",
    endDate: "2026-08-12",
    totalPrice: 25000 * 7,
    message: "여행 다녀오면서 스냅 촬영에 사용했습니다.",
    shippingAddress: SHIPPING_TEMPLATE("m1"),
    shipping: { carrier: "롯데택배", trackingNumber: "119284736450" },
    receiptEvidence: {
      photoUrls: ["evidence-r5-receipt-1", "evidence-r5-receipt-2"],
      condition: "양호",
      memo: "바디, 배터리, 충전기 모두 정상 수령.",
      recordedAt: "2026-08-05",
    },
    returnEvidence: null,
    createdAt: "2026-08-01",
  },
  {
    id: "r6",
    equipmentId: "eq5",
    ownerId: "m1",
    ownerName: userName("m1"),
    borrowerId: "m3",
    borrowerName: userName("m3"),
    status: "RETURN_REQUESTED",
    startDate: "2026-07-28",
    endDate: "2026-08-04",
    totalPrice: 20000 * 7,
    message: "홈파티 스크리닝용으로 사용했습니다.",
    shippingAddress: SHIPPING_TEMPLATE("m3"),
    shipping: { carrier: "우체국택배", trackingNumber: "530291847362" },
    receiptEvidence: {
      photoUrls: ["evidence-r6-receipt-1", "evidence-r6-receipt-2"],
      condition: "양호",
      memo: "렌즈, 전원 케이블 이상 없음.",
      recordedAt: "2026-07-28",
    },
    returnEvidence: {
      photoUrls: ["evidence-r6-return-1", "evidence-r6-return-2"],
      condition: "사용감 있음",
      memo: "본체 하단에 미세 스크래치가 생겼습니다.",
      recordedAt: "2026-08-04",
    },
    createdAt: "2026-07-25",
  },
  {
    id: "r7",
    equipmentId: "eq6",
    ownerId: "m4",
    ownerName: userName("m4"),
    borrowerId: "m1",
    borrowerName: userName("m1"),
    status: "COMPLETED",
    startDate: "2026-07-15",
    endDate: "2026-07-20",
    totalPrice: 18000 * 5,
    message: "친구들과 게임 모임에서 사용했습니다.",
    shippingAddress: SHIPPING_TEMPLATE("m1"),
    shipping: { carrier: "CJ대한통운", trackingNumber: "774610239485" },
    receiptEvidence: {
      photoUrls: ["evidence-r7-receipt-1", "evidence-r7-receipt-2"],
      condition: "양호",
      memo: "컨트롤러 2개, 타이틀 3종 모두 정상.",
      recordedAt: "2026-07-15",
    },
    returnEvidence: {
      photoUrls: ["evidence-r7-return-1", "evidence-r7-return-2"],
      condition: "양호",
      memo: "이상 없이 잘 사용했습니다.",
      recordedAt: "2026-07-20",
    },
    createdAt: "2026-07-12",
  },
  {
    id: "r8",
    equipmentId: "eq8",
    ownerId: "m5",
    ownerName: userName("m5"),
    borrowerId: "m1",
    borrowerName: userName("m1"),
    status: "REJECTED",
    startDate: "2026-08-18",
    endDate: "2026-08-22",
    totalPrice: 16000 * 4,
    message: "여행 가서 작업용으로 쓰려고 합니다.",
    shippingAddress: SHIPPING_TEMPLATE("m1"),
    shipping: null,
    receiptEvidence: null,
    returnEvidence: null,
    createdAt: "2026-08-13",
  },
];

export const REPORTS: Report[] = [
  {
    id: "rep1",
    rentalId: "r7",
    reporterId: "m1",
    reporterName: userName("m1"),
    reportedUserId: "m4",
    reportedUserName: userName("m4"),
    equipmentName: "플레이스테이션5 슬림",
    reason: "장비 파손 / 상태 불일치",
    detail: "컨트롤러 스틱 조작감이 반납 후 이상해졌다는 안내를 받았는데, 수령 당시부터 그랬던 것 같습니다.",
    photoUrls: ["report-rep1-1"],
    status: "검토중",
    createdAt: "2026-07-21",
    progress: [
      { label: "접수 완료", reachedAt: "2026-07-21" },
      { label: "관리자 검토", reachedAt: "2026-07-22" },
      { label: "처리 완료", reachedAt: null },
    ],
    disputeEligible: true,
  },
  {
    id: "rep2",
    rentalId: "r3",
    reporterId: "m1",
    reporterName: userName("m1"),
    reportedUserId: "m4",
    reportedUserName: userName("m4"),
    equipmentName: "캐논 EOS R6 Mark II",
    reason: "반납 지연 / 미반납",
    detail: "배송이 안내드린 날짜보다 이틀 늦게 출발했습니다.",
    photoUrls: [],
    status: "접수",
    createdAt: "2026-08-13",
    progress: [
      { label: "접수 완료", reachedAt: "2026-08-13" },
      { label: "관리자 검토", reachedAt: null },
      { label: "처리 완료", reachedAt: null },
    ],
    disputeEligible: false,
  },
  {
    id: "rep3",
    rentalId: "r8",
    reporterId: "m1",
    reporterName: userName("m1"),
    reportedUserId: "m5",
    reportedUserName: userName("m5"),
    equipmentName: "LG 그램 17",
    reason: "부적절한 언행",
    detail: "대여 요청 거절 사유를 묻는 과정에서 무례한 답변을 받았습니다.",
    photoUrls: [],
    status: "처리완료",
    createdAt: "2026-08-13",
    progress: [
      { label: "접수 완료", reachedAt: "2026-08-13" },
      { label: "관리자 검토", reachedAt: "2026-08-13" },
      { label: "처리 완료", reachedAt: "2026-08-14" },
    ],
    disputeEligible: false,
  },
  {
    id: "rep4",
    rentalId: "r6",
    reporterId: "m3",
    reporterName: userName("m3"),
    reportedUserId: "m1",
    reportedUserName: userName("m1"),
    equipmentName: "LG 시네빔 4K",
    reason: "장비 파손 / 상태 불일치",
    detail: "반납 확인 과정에서 등록자가 파손을 주장하고 있는데, 원래 있던 흠집입니다.",
    photoUrls: ["report-rep4-1", "report-rep4-2"],
    status: "검토중",
    createdAt: "2026-08-05",
    progress: [
      { label: "접수 완료", reachedAt: "2026-08-05" },
      { label: "관리자 검토", reachedAt: "2026-08-06" },
      { label: "처리 완료", reachedAt: null },
    ],
    disputeEligible: true,
  },
];

export const DISPUTES: Dispute[] = [
  {
    id: "d1",
    reportId: "rep4",
    reason: "반납 장비 파손 여부에 대한 이견",
    partyNames: [userName("m1"), userName("m3")],
    claimAmount: 50000,
    equipmentName: "LG 시네빔 4K",
    createdAt: "2026-08-06",
    adjustmentDueDate: "2026-08-20",
    evidencePhotoUrls: ["dispute-d1-1", "dispute-d1-2"],
    status: "조정중",
  },
  {
    id: "d2",
    reportId: "rep1",
    reason: "컨트롤러 파손 책임 소재 다툼",
    partyNames: [userName("m1"), userName("m4")],
    claimAmount: 30000,
    equipmentName: "플레이스테이션5 슬림",
    createdAt: "2026-07-23",
    adjustmentDueDate: "2026-08-06",
    evidencePhotoUrls: ["dispute-d2-1"],
    status: "접수",
  },
  {
    id: "d3",
    reportId: "rep3",
    reason: "부적절한 언행에 대한 계정 제재 요청",
    partyNames: [userName("m1"), userName("m5")],
    claimAmount: 0,
    equipmentName: "LG 그램 17",
    createdAt: "2026-08-14",
    adjustmentDueDate: "2026-08-21",
    evidencePhotoUrls: [],
    status: "종결",
  },
];

export const ADMIN_MEMBERS: AdminMember[] = [
  {
    id: "m1",
    name: userName("m1"),
    email: "kimdohyun@example.com",
    phoneMasked: "010-****-5678",
    joinedAt: "2025-11-02",
    lastActiveAt: "2026-08-14",
    reportCount: 1,
    borrowedCount: 4,
    lentCount: 3,
    registeredEquipmentCount: 3,
    overdueCount: 1,
    status: "정상",
  },
  {
    id: "m2",
    name: userName("m2"),
    email: "seoyeon.lee@example.com",
    phoneMasked: "010-****-6789",
    joinedAt: "2025-09-14",
    lastActiveAt: "2026-08-12",
    reportCount: 0,
    borrowedCount: 1,
    lentCount: 1,
    registeredEquipmentCount: 1,
    overdueCount: 0,
    status: "정상",
  },
  {
    id: "m3",
    name: userName("m3"),
    email: "junhyuk.park@example.com",
    phoneMasked: "010-****-7890",
    joinedAt: "2026-01-20",
    lastActiveAt: "2026-08-10",
    reportCount: 1,
    borrowedCount: 2,
    lentCount: 0,
    registeredEquipmentCount: 0,
    overdueCount: 0,
    status: "경고",
  },
  {
    id: "m4",
    name: userName("m4"),
    email: "yuna.choi@example.com",
    phoneMasked: "010-****-8901",
    joinedAt: "2025-12-05",
    lastActiveAt: "2026-08-13",
    reportCount: 2,
    borrowedCount: 0,
    lentCount: 2,
    registeredEquipmentCount: 2,
    overdueCount: 0,
    status: "정상",
  },
  {
    id: "m5",
    name: userName("m5"),
    email: "minsu.jung@example.com",
    phoneMasked: "010-****-9012",
    joinedAt: "2025-08-30",
    lastActiveAt: "2026-08-01",
    reportCount: 1,
    borrowedCount: 0,
    lentCount: 2,
    registeredEquipmentCount: 2,
    overdueCount: 0,
    status: "정지",
  },
];

export const ADMIN_HISTORY: AdminHistoryEntry[] = [
  {
    id: "h1",
    occurredAt: "2026-08-14 10:20",
    adminName: "관리자A",
    action: "회원 상태를 '정지'로 변경",
    targetLabel: userName("m5"),
    targetType: "member",
    targetId: "m5",
  },
  {
    id: "h2",
    occurredAt: "2026-08-13 16:05",
    adminName: "관리자B",
    action: "신고를 '처리완료'로 전환",
    targetLabel: "부적절한 언행 신고",
    targetType: "report",
    targetId: "rep3",
  },
  {
    id: "h3",
    occurredAt: "2026-08-06 09:40",
    adminName: "관리자A",
    action: "신고를 분쟁으로 전환",
    targetLabel: "LG 시네빔 4K 파손 분쟁",
    targetType: "dispute",
    targetId: "d1",
  },
  {
    id: "h4",
    occurredAt: "2026-07-23 14:12",
    adminName: "관리자B",
    action: "분쟁 접수 처리",
    targetLabel: "플레이스테이션5 슬림 파손 분쟁",
    targetType: "dispute",
    targetId: "d2",
  },
  {
    id: "h5",
    occurredAt: "2026-06-02 11:30",
    adminName: "관리자A",
    action: "장비 상태를 '공개'로 승인",
    targetLabel: "소니 A7C II 미러리스",
    targetType: "equipment",
    targetId: "eq1",
  },
];

const ACTIVE_RENTAL_STATUSES = new Set([
  "PAID",
  "SHIPPING",
  "RENTING",
  "RETURN_UPLOAD",
  "RETURN_REQUESTED",
]);

/** An equipment is unavailable to browse/request while it has a non-terminal rental. */
export function isEquipmentRented(equipmentId: string, rentals: Rental[]): boolean {
  return rentals.some(
    (rental) => rental.equipmentId === equipmentId && ACTIVE_RENTAL_STATUSES.has(rental.status),
  );
}

const RESERVED_RENTAL_STATUSES = new Set([
  "PENDING",
  "PAID",
  "SHIPPING",
  "RENTING",
  "RETURN_UPLOAD",
  "RETURN_REQUESTED",
]);

/** ISO dates already booked (or pending approval) for an equipment — disabled in the date-range picker. */
export function getBookedDates(equipmentId: string, rentals: Rental[]): Set<string> {
  const dates = new Set<string>();
  for (const rental of rentals) {
    if (rental.equipmentId !== equipmentId || !RESERVED_RENTAL_STATUSES.has(rental.status)) continue;
    let cursor = parseISODate(rental.startDate);
    const end = parseISODate(rental.endDate);
    while (cursor.getTime() <= end.getTime()) {
      dates.add(toISODate(cursor));
      cursor = new Date(cursor.getFullYear(), cursor.getMonth(), cursor.getDate() + 1);
    }
  }
  return dates;
}
